### ISSUE TITLE
Refatoracao TaskModel para arquivos mais especificos

### ISSUE THREAD

**Issue by MoysesAz** [CaioFaSoares/baskets#1]
https://github.com/CaioFaSoares/baskets/blob/a0b948f43c5931915e75667cfbbcabb7d73a776f/syrup/Source%20Code/Models/TaskModel.swift#L11-L46

Seria interessante a criacao dos models em arquivos separados, seguindo o principio da responsabilidade unica. Criar arquivos especificos com o nome do que tem dentro dele acaba facilitando na hora de implementar ou refatorar, diminuindo o tempo para encontrar o que voce quer. Levando isso para um contexto onde voce passa o dia procurando e alterando arquivos voce acaba ganhando  muito tempo.

Exemplo:
     - Models
         - Projects.swift
         - Basket.swift
         - Casks.swift
         - Syrups.swift

O conceito de ganhar mais tempo utilizando o principio da responsabilidade unica na arquitetura faz sentido pra vc?
segue um link falando mais sobre isso:
https://medium.com/@engnogueirawgn/princ%C3%ADpio-da-responsabilidade-%C3%BAnica-srp-f6cbf22330d6

**Comment by CaioFaSoares** [comment]
De fato. Vou abrir a branch e trabalhar nisso.
